version: '3.5'

services:
  minio:
    image: minio/minio:RELEASE.2021-03-04T00-53-13Z
    container_name: minio
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9000:9000
    command: server /data
    networks:
      - imdb-etl
    restart: always

networks:
  imdb-etl:
    external:
      name: imdb-etl

volumes:
  minio-data:
  
