version: '3.5'

services:
  minio:
    image: minio/minio:RELEASE.2021-03-04T00-53-13Z
    container_name: minio
    volumes:
      - minio-volume:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    ports:
      - 9000:9000
    command: server /data
    networks:
      - imdb-etl
    restart: always

  imdb_postgres:
    image: postgres:12.6-alpine
    container_name: imdb_postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=imdb
    ports:
      - "5433:5432"
    networks:
      - imdb-etl
    restart: always
    healthcheck:
      test: pg_isready -U admin -d imdb -h localhost -q
 
networks:
  imdb-etl:
    external:
      name: imdb-etl

volumes:
  minio-volume:
  postgres-volume:
