{
 "title": "IMDb",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Genres",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT genres, COUNT(genres)\r\nFROM\r\n(\r\n  SELECT genre_1 as genres FROM titles\r\n  UNION ALL\r\n  SELECT genre_2 as genres FROM titles\r\n  UNION ALL\r\n  SELECT genre_3 as genres FROM titles  \r\n) as t \r\nWHERE genres != '\\N' \r\nGROUP BY genres\r\nORDER BY count"
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT primary_title as \"Title\",\r\n       total_episodes as \"Number of Episodes\"\r\nFROM titles\r\nJOIN episodes ON titles.id = episodes.title_id\r\nORDER BY total_episodes DESC\r\nLIMIT 25;"
    }
   ]
  },
  {
   "title": "Adult Film",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n(SELECT COUNT(is_adult) FROM titles WHERE is_adult = True) as \"Adult\",\n(SELECT COUNT(is_adult) FROM titles WHERE is_adult = False) as \"Non-adult\""
    }
   ]
  },
  {
   "title": "Most Apperances (Casts)",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT name, count(name) as c FROM casts \r\njoin titles_casts on cast_id = id\r\ngroup by name order by c desc limit 50;"
    }
   ]
  },
  {
   "title": "Most Appearances (Crew)",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT name, count(name) as c FROM crew \r\njoin titles_crew on crew_id = id\r\ngroup by name order by c desc limit 50;"
    }
   ]
  }
 ]
}